POST http://localhost:3001/api/messages
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pa2FMZXBwaWFobyIsImlkIjoiNWVlNTQ2YzgxYmY5ZGYxYjBjMTBjZDExIiwiaWF0IjoxNTkyMTEzNDE5fQ.lAmiLShxtCB8YxdFTBlCn3tTy8HoXYSEt3wNYa71AGY

{
    "content": "Hello! How is everybody doing?"
}
###
GET http://localhost:3001/api/messages

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "demo",
    "name": "Demo User",
    "password": "salasana"
}

###
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "Demouser",
    "password": "Salasana1"
}

